// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MadhubaniArt",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "MadhubaniArt",
            targets: ["AppModule"],
            bundleIdentifier: "com.DemoDebugging.MadhubaniArt",
            teamIdentifier: "2Z3FULAVPS",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .photoLibrary(purposeString: "This app needs to save your Madhubani art to your photo library so you can share Bihar's heritage with the world")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)